import './globals.css'
import Footer from '../components/footer/Footer'
import Navbar from '../components/navbar/Navbar'
import {ThemeProvider} from '../context/Themecontext'



export const metadata = {
  title: 'Bambo App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">


      <body >
        <ThemeProvider>
        <div className="container">
        <Navbar />
        {children}
        <Footer />
        </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
